### ISSUE TITLE
[Logs] long values are shown incomplete in history

### ISSUE THREAD

**Issue by SimonHeimberg** [EmchBerger/cube-common-bundle#40] opened 2018-02-07 15:16 UTC
The value for **associations** is at maximum 255 characters in length (because of column label length in audit_log).
We should at least indicate a shortened value in history.

This generates problems with html code. It is returned incomplete.
Possibilities to handle this case:
 * clean up (shortened) html strings with tidy: https://secure.php.net/manual/en/tidy.examples.php#89334
 * do not show (all) html formatting: `{{ some_html\|striptags('<br><p>') }} {# only keep br and p #}`
 * do not show all html formatting for shortened texts
 * show full value (must be read separately from audit_log)

**Comment by SimonHeimberg** [comment] 2018-02-07 21:20
to view some of the related associations (in db reservations): SELECT * FROM `pa_reservations`.`audit_associations` WHERE `id` in (247871, 247889, 274818, 274836)

**Comment by markussc** [comment] 2018-02-07 21:36
Suggest to use this advanced truncate filter: https://github.com/dzango/TwigTruncateExtension
I am currently figuring out how to apply it to achieve best results

**Comment by markussc** [comment] 2018-02-07 23:09
suggest to close this. It's implemented in https://github.com/EmchBerger/projectassistant/pull/1548

**Comment by SimonHeimberg** [comment] 2018-02-09 11:08
We should still show that a value is incomplete if it is not html.

**Comment by MartinRosserEB** [comment] 2018-02-09 11:10
Incomplete HTML tags (e.g. &nbs for truncated &nbsp;) confirmed to still be in the log. Minor issue, visible e.g. in reservation 2507.

**Comment by markussc** [comment] 2018-02-09 13:54
What we could do is remove the last word from the string before sending it to the truncate macro. This is a bit tricky since in order to do this, we first have to strip tags (otherwise there are no separate words in the string).

**Comment by SimonHeimberg** [comment] 2018-02-12 06:57
Stripping last word done in 99a41ebf46

**Closed** 2020-05-29 12:40 UTC
Labels: bug
